#Tile descriptions

scene = {1: 'meadow desc',
         2: 'meadow desc',
         3: 'meadow desc',
         4: 'dragonlands desc',
         5: 'dragonlands desc',
         6: 'dragonlands desc',
         7: 'meadow desc',
         8: 'meadow desc',
         9: 'meadow desc',
         10: 'dragonlands desc',
         11: 'dragonlands desc',
         12: 'dragonlands desc',
         13: 'meadow desc',
         14: 'meadow desc',
         15: 'meadow desc',
         16: 'dragonlands desc',
         17: 'dragonlands desc',
         18: 'dragonlands desc',
         19: 'desert desc',
         20: 'desert desc',
         21: 'desert desc',
         22: 'forest desc',
         23: 'forest desc',
         24: 'forest desc',
         25: 'desert desc',
         26: 'desert desc',
         27: 'desert desc',
         28: 'forest desc',
         29: 'forest desc',
         30: 'forest desc',
         31: 'desert desc',
         32: 'desert desc',
         33: 'desert desc',
         34: 'forest desc',
         35: 'forest desc',
         36: 'forest desc'
	}   
  